### ISSUE TITLE
Help needed : Error 502 Bad Gateway when accessing RTL

### ISSUE THREAD

**Issue by Nisaba** [btcpayserver/btcpayserver-docker#346] opened 2020-08-05 18:55 UTC
Hello,

When I want to got to RTL : 
Server settings / Services / Ride the Lightning server / See information / Browser connection 

-> I get a 502 Bad Gateway error on the browser.

Thank you for your help

**Comment by Eskyee** [comment] 2020-08-05 19:04
What version number. is your BTCPay node running ?? 
also please check this issue, from a few days ago,  I had mentioned it to @NicolasDorier & the RTL team 
https://github.com/Ride-The-Lightning/RTL/issues/391

**Comment by Eskyee** [comment] 2020-08-05 19:18
I just tested on a lunanode BTCPayServer v1.0.5.4
and Server settings / Services / Ride the Lightning server link working ok. for me.

but I did spot this error on a Azure build...and bad gateway.. on my Azure server. was told this fix after by RTL team.
RTL config path should be set to ‘/data/’ only, NOT ‘/data/RTL.conf/‘.      
but still not had time to test yet. 

Nisaba can you check your RTL container logs ??

**Comment by Nisaba** [comment] 2020-08-05 19:23
OK,
Thanks for the information.
I've the v1.0.5.3 version.

I will ask to my admin and keep you informed

**Comment by saubyk** [comment] 2020-08-06 00:29
> I just tested on a lunanode BTCPayServer v1.0.5.4
> and Server settings / Services / Ride the Lightning server link working ok. for me.
> 
> but I did spot this error on a Azure build...and bad gateway.. on my Azure server. was told this fix after by RTL team.
> RTL config path should be set to ‘/data/’ only, NOT ‘/data/RTL.conf/‘.
> but still not had time to test yet.
> 
> Nisaba can you check your RTL container logs ??
> I spotted this error. from v1.0.5.3

Hey @Eskyee please note a correct the config path should be `/data`

**Comment by NicolasDorier** [comment] 2020-08-06 01:57
@Nisaba are you fully synched?

**Comment by NicolasDorier** [comment] 2020-08-06 03:10
@Nisaba also have you updated to latest version with `btcpay-update.sh`?

**Comment by mankwes** [comment] 2020-08-06 09:36
Hi all, i m on the same team with @Nisaba, we did the update with btcpay-update.sh and the docker is updated to  v1.0.5.4.
We check also on the config path is /data.

those are the log
```
docker logs --tail 100 generated_lnd_bitcoin_rtl_1
Error: No such container: generated_lnd_bitcoin_rtl_1
```
```
docker logs --tail 10 btcpayserver_lnd_bitcoin
2020-08-06 09:26:56.361 [INF] CRTR: Processed channels=0 updates=31 nodes=1 in last 59.999876734s
2020-08-06 09:27:42.753 [INF] DISC: Broadcasting 140 new announcements in 14 sub batches

```
But still get the 502 Bad Gateway.

**Comment by ShahanaFarooqui** [comment] 2020-08-06 12:50
@mankwes, @NicolasDorier, @Eskyee 

Are you running it on `localhost` or remote? localhost is the default value for `HOST` setting but if you are running it remotely then you need to provide HOST environment value.

https://github.com/Ride-The-Lightning/RTL/issues/391#issuecomment-666374818

**Comment by mankwes** [comment] 2020-08-06 13:08
@ShahanaFarooqui  i'm running it on remote domain name.

**Comment by Eskyee** [comment] 2020-08-06 14:39
I'm running on remote

**Comment by NicolasDorier** [comment] 2020-08-06 15:19
@mankwes  wrong command, should be

`docker logs generated_bitcoin_rtl_1`

**Comment by mankwes** [comment] 2020-08-06 15:26
Sorry here are the log
```
 docker logs generated_bitcoin_rtl_1
Server is up and running, please open the UI at http://localhost:3000
```

**Comment by rockstardev** [comment] 2020-08-06 22:05
I can confirm problem on another instance. Nothing useful in logs.

**Comment by saubyk** [comment] 2020-08-06 22:47
> I can confirm problem on another instance. Nothing useful in logs. On nginx getting:
> 
> `[error] 22#22: *14866 connect() failed (111: Connection refused) while connecting to upstream, client: [my ip] ... upstream: "http://172.18.0.9:3000/rtl/api/authenticate/cookie?access-key=38b46ac12d5xxxxx..."`

Hi @rockstardev has there any change been made recently for the Nginx setting?
Ideally, Nginx need not query rtl with the IP address in the url, since Nginx and RTL are on the same host.

There should be two possible ways to resolve this:
- Set the 'HOST' env variable for RTL to the IP address of the host, in docker compose.
or
- Change Nginx config to query RTL on localhost e.g. `http://localhost:3000/rtl/api/authenticate/cookie?access-key=38b46ac12d5xxxxx...`

**Comment by rockstardev** [comment] 2020-08-06 22:54
There hasn't been any change in Nginx setting.

@saubyk deleting `"host": "localhost"` from RTL-Config.json resolves the issue.

**Comment by saubyk** [comment] 2020-08-06 23:05
@rockstardev missed the container nuance (docker noob still) :-)
Deleting the localhost setting for RTL-Config.json, results in host IP address being chosen as the default I guess, which is how it should be serving.

**Comment by rockstardev** [comment] 2020-08-06 23:13
@saubyk yeah... I'm not sure we can fix it some other way. You do expose 3000 but you are not binding port to outside Docker network (with `ports` setting). So we would need some proxy process within your container in order to be able to hit it with localhost:3000.

I'm not sure if @NicolasDorier has some nginx trick up his sleeve... where we could set host... but it's question how your process would return response to outside if host is "localhost".

**Comment by saubyk** [comment] 2020-08-06 23:19
@rockstardev I don't think RTL should serve on the localhost in this case.
We can ensure that the default `RTL-Config.json` which is generated by RTL, does not contain the `host` config. That should address the problem.

**Comment by rockstardev** [comment] 2020-08-06 23:21
That would be great. If you publish the update on your containers let us know so we can bump version asap to stop people from deploying instances that'll need to be manually fixed.

**Comment by saubyk** [comment] 2020-08-07 00:15
@rockstardev Docker image tagged with v0.8.4:
https://hub.docker.com/r/shahanafarooqui/rtl/tags

**Comment by rockstardev** [comment] 2020-08-07 09:17
GJ... @NicolasDorier merged with Emperor speed.

**Closed** 2020-08-07 09:16 UTC

**Comment by NicolasDorier** [comment] 2020-08-10 13:54
ugh thanks @rockstardev I think we should mention that on the doc? Or maybe let people know about the workaround so if noobs get stucks we can help.

**Comment by NicolasDorier** [comment] 2020-08-10 13:55
ping @Kukks @pavlenex if noobs on channel see problems

https://github.com/btcpayserver/btcpayserver-docker/issues/346#issuecomment-670230046

The command line though is not good, as somebody not knowing how to use vim will not be able to fix the sissue.

**Comment by pavlenex** [comment] 2020-08-10 15:06
From what I understood this only happened to newly deployed instanced on v1.0.5.3 so probably a small number of people are affected. I haven't seen many people complaining tbh. But they can easily re-deploy if cli is problem, this only affects those who want to use RTL.
